### ISSUE TITLE
Update the db dump

### ISSUE THREAD

**Issue by Robert-Hansen** [wbbly/graphql-engine#1]
Hi @athlonUA,

I'm trying to setup this project, but i'm running into some issues with the database looks like the dump in this repository isn't update to date with the time api so it causes a lot of issues when it tries to insert into columns that doesn't exists.

**Comment by athlonUA** [comment]
@Robert-Hansen Hello mate! Thanks for your request. Yeah, I see the dump is not actual. I'll check it a little bit later

**Comment by athlonUA** [comment]
@Robert-Hansen The db dump was updated

**Comment by Robert-Hansen** [comment]
@athlonUA  awesome! thanks a lot
